title: Life among the ruins
description: My digital art, photo and coding Blog!
author: Mike Ravenblack
avatar: /avatar.jpg

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: solarized

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
